name: Convert proposal.docx

on:
  push:
    paths:
      - 'babs/docs/proposal.docx'
  workflow_dispatch:

jobs:
  run-remote-workflow:
    uses: ChristopherBarrington/babs-workflows/.github/workflows/convert-proposal-docx.yml@convert-proposal
    with:
      target-file: 'babs/docs/proposal.docx'
