name: Convert experiment_table.xlsx

on:
  push:
    paths:
      - 'babs/docs/experiment_table.xlsx'
  workflow_dispatch:

jobs:
  run-remote-workflow:
    uses: ChristopherBarrington/babs-workflows/.github/workflows/convert-experiment-table-xlsx.yml@main
    with:
      target-file: 'babs/docs/experiment_table.xlsx'
