name: Convert experiment_table.xlsx

on:
  push:
    paths:
      - 'babs/docs/experiment_table.xlsx'
  workflow_dispatch:

jobs:
  compliance:
    uses: ChristopherBarrington/babs-workflows/.github/workflows/convert-experiment-table-to-csv.yml@main
    with:
      FOOBAR: foobar
      TABLE_FILE: 'babs/docs/experiment_table.xlsx'
