name: Convert experiment_table.xlsx

on:
  push:
    paths:
      - 'babs/docs/experiment_table.xlsx'
  workflow_dispatch:

jobs:
  compliance:
    uses: ChristopherBarrington/xlsx2csv-action/.github/workflows/convert-experiment-table-to-csv.yml@main
