name: react to issue comment

on:
  issue_comment:
    types: [created, edited]
jobs:
 dump:
  runs-on: ubuntu-latest
  steps:
  - name: print body
    env:
      BODY: ${{ github.event.comment.body }}
    run: echo "$BODY"
