name: react to issue comment

on:
  issue_comment:
    types: [created, edited]
jobs:
 print:
  runs-on: ubuntu-latest
  steps:
  - name: print body
    env:
      BODY: ${{ github.event.comment.body }}
    run: echo "$BODY"
 dump:
  runs-on: ubuntu-latest
  steps:
  - name: $github
    run:   echo "$GITHUB_CONTEXT"
    env:
     GITHUB_CONTEXT: ${{ toJson(github) }}
